// <auto-generated />
using ElectroComApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectroComApi.Migrations
{
    [DbContext(typeof(ElectroComDbContext))]
    [Migration("20250717063849_RenamePriceAndDeliveryColumnsElectroCom")]
    partial class RenamePriceAndDeliveryColumnsElectroCom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectroComApi.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "PROD001",
                            DeliveryDays = 2,
                            DiscountPercentage = 0.03m,
                            Price = 145.00m,
                            ProductName = "Smartphone",
                            Stock = 80
                        },
                        new
                        {
                            ProductId = "PROD002",
                            DeliveryDays = 1,
                            DiscountPercentage = 0.05m,
                            Price = 52.00m,
                            ProductName = "Wireless Earbuds",
                            Stock = 300
                        },
                        new
                        {
                            ProductId = "PROD003",
                            DeliveryDays = 3,
                            DiscountPercentage = 0.00m,
                            Price = 1180.00m,
                            ProductName = "Laptop",
                            Stock = 45
                        },
                        new
                        {
                            ProductId = "PROD007",
                            DeliveryDays = 2,
                            DiscountPercentage = 0.07m,
                            Price = 90.00m,
                            ProductName = "Gaming Keyboard",
                            Stock = 120
                        },
                        new
                        {
                            ProductId = "PROD008",
                            DeliveryDays = 5,
                            DiscountPercentage = 0.10m,
                            Price = 110.00m,
                            ProductName = "External SSD",
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
