// <auto-generated />
using ElectroComApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectroComApi.Migrations
{
    [DbContext(typeof(ElectroComDbContext))]
    [Migration("20250716170648_InitialCreateElectroCom")]
    partial class InitialCreateElectroCom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectroComApi.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "PROD001",
                            BasePrice = 145.00m,
                            ProductName = "Smartphone",
                            Stock = 80
                        },
                        new
                        {
                            ProductId = "PROD002",
                            BasePrice = 52.00m,
                            ProductName = "Wireless Earbuds",
                            Stock = 300
                        },
                        new
                        {
                            ProductId = "PROD003",
                            BasePrice = 1180.00m,
                            ProductName = "Laptop",
                            Stock = 45
                        },
                        new
                        {
                            ProductId = "PROD007",
                            BasePrice = 90.00m,
                            ProductName = "Gaming Keyboard",
                            Stock = 120
                        },
                        new
                        {
                            ProductId = "PROD008",
                            BasePrice = 110.00m,
                            ProductName = "External SSD",
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
