// <auto-generated />
using GadgetCentralApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GadgetCentralApi.Migrations
{
    [DbContext(typeof(GadgetCentralDbContext))]
    [Migration("20250716172439_InitialCreateGadgetCentral")]
    partial class InitialCreateGadgetCentral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GadgetCentralApi.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "PROD001",
                            BasePrice = 155.00m,
                            ProductName = "Smartphone",
                            Stock = 90
                        },
                        new
                        {
                            ProductId = "PROD003",
                            BasePrice = 1250.00m,
                            ProductName = "Laptop",
                            Stock = 60
                        },
                        new
                        {
                            ProductId = "PROD009",
                            BasePrice = 60.00m,
                            ProductName = "Gaming Mouse",
                            Stock = 200
                        },
                        new
                        {
                            ProductId = "PROD010",
                            BasePrice = 40.00m,
                            ProductName = "Webcam",
                            Stock = 75
                        },
                        new
                        {
                            ProductId = "PROD002",
                            BasePrice = 48.00m,
                            ProductName = "Wireless Earbuds",
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
