// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechWorldApi.Data;

#nullable disable

namespace TechWorldApi.Migrations
{
    [DbContext(typeof(TechWorldDbContext))]
    [Migration("20250717062148_AddDiscountAndDeliveryToProducts")]
    partial class AddDiscountAndDeliveryToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechWorldApi.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BaseDeliveryDays")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "PROD001",
                            BaseDeliveryDays = 3,
                            BasePrice = 150.00m,
                            DiscountPercentage = 0.05m,
                            ProductName = "Smartphone",
                            Stock = 100
                        },
                        new
                        {
                            ProductId = "PROD002",
                            BaseDeliveryDays = 2,
                            BasePrice = 50.00m,
                            DiscountPercentage = 0.10m,
                            ProductName = "Wireless Earbuds",
                            Stock = 250
                        },
                        new
                        {
                            ProductId = "PROD003",
                            BaseDeliveryDays = 4,
                            BasePrice = 1200.00m,
                            DiscountPercentage = 0.00m,
                            ProductName = "Laptop",
                            Stock = 50
                        },
                        new
                        {
                            ProductId = "PROD004",
                            BaseDeliveryDays = 1,
                            BasePrice = 25.00m,
                            DiscountPercentage = 0.02m,
                            ProductName = "USB Cable",
                            Stock = 500
                        },
                        new
                        {
                            ProductId = "PROD005",
                            BaseDeliveryDays = 7,
                            BasePrice = 300.00m,
                            DiscountPercentage = 0.15m,
                            ProductName = "Gaming Console",
                            Stock = 0
                        },
                        new
                        {
                            ProductId = "PROD006",
                            BaseDeliveryDays = 3,
                            BasePrice = 75.00m,
                            DiscountPercentage = 0.08m,
                            ProductName = "Smartwatch",
                            Stock = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
